server:
  port: 10190
  ssl:
    key-store: "classpath:config/service-keystore.p12"
    key-store-password: "password"
    key-store-type: PKCS12

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zowex-java-service

zowe:
  apiml:
    discovery:
      enabled: true
    service:
      id: zowex-java
      title: "Zowex Java Service"
      description: "Zowex Java FFM Service for z/OS"
      version: "0.5.0"
      routingUrl: "https://localhost:${server.port}"

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:10011/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    statusPageUrlPath: /application/health
    homePageUrlPath: /
    healthCheckUrlPath: /application/health
