/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zowe_zowex_zos_security_jni_Secur */

#ifndef _Included_org_zowe_zowex_zos_security_jni_Secur
#define _Included_org_zowe_zowex_zos_security_jni_Secur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zowe_zowex_zos_security_jni_Secur
 * Method:    createSecurityEnvironment
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zowe_zowex_zos_security_jni_Secur_createSecurityEnvironment
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_zowe_zowex_zos_security_jni_Secur
 * Method:    createSecurityEnvironmentByDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zowe_zowex_zos_security_jni_Secur_createSecurityEnvironmentByDaemon
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_zowe_zowex_zos_security_jni_Secur
 * Method:    removeSecurityEnvironment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zowe_zowex_zos_security_jni_Secur_removeSecurityEnvironment
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_zowex_zos_security_jni_Secur
 * Method:    getLastErrno2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zowe_zowex_zos_security_jni_Secur_getLastErrno2
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_zowex_zos_security_jni_Secur
 * Method:    setApplid
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zowe_zowex_zos_security_jni_Secur_setApplid
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
