/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// Code generated by generateTypes.ts. DO NOT EDIT.

#ifndef RESPONSES_HPP
#define RESPONSES_HPP

#include "../validator.hpp"

struct Dataset {};
ZJSON_SCHEMA(Dataset,
    FIELD_REQUIRED(name, STRING),
    FIELD_OPTIONAL(alloc, NUMBER),
    FIELD_OPTIONAL(allocx, NUMBER),
    FIELD_OPTIONAL(blksize, NUMBER),
    FIELD_OPTIONAL(cdate, STRING),
    FIELD_OPTIONAL(dataclass, STRING),
    FIELD_OPTIONAL(devtype, STRING),
    FIELD_OPTIONAL(dsntype, STRING),
    FIELD_OPTIONAL(dsorg, STRING),
    FIELD_OPTIONAL(edate, STRING),
    FIELD_OPTIONAL(encrypted, BOOL),
    FIELD_OPTIONAL(lrecl, NUMBER),
    FIELD_OPTIONAL(mgmtclass, STRING),
    FIELD_OPTIONAL(migrated, BOOL),
    FIELD_OPTIONAL(multivolume, BOOL),
    FIELD_OPTIONAL(primary, NUMBER),
    FIELD_OPTIONAL(rdate, STRING),
    FIELD_OPTIONAL(recfm, STRING),
    FIELD_OPTIONAL(secondary, NUMBER),
    FIELD_OPTIONAL(spacu, STRING),
    FIELD_OPTIONAL(storclass, STRING),
    FIELD_OPTIONAL(usedp, NUMBER),
    FIELD_OPTIONAL(usedx, NUMBER),
    FIELD_OPTIONAL(volser, STRING),
    FIELD_OPTIONAL_ARRAY(volsers, STRING)
);

struct DsMember {};
ZJSON_SCHEMA(DsMember,
    FIELD_REQUIRED(name, STRING),
    FIELD_OPTIONAL(user, STRING),
    FIELD_OPTIONAL(vers, NUMBER),
    FIELD_OPTIONAL(mod, NUMBER),
    FIELD_OPTIONAL(c4date, STRING),
    FIELD_OPTIONAL(m4date, STRING),
    FIELD_OPTIONAL(mtime, STRING),
    FIELD_OPTIONAL(cnorc, NUMBER),
    FIELD_OPTIONAL(inorc, NUMBER),
    FIELD_OPTIONAL(mnorc, NUMBER),
    FIELD_OPTIONAL(sclm, STRING)
);

struct Job {};
ZJSON_SCHEMA(Job,
    FIELD_REQUIRED(id, STRING),
    FIELD_REQUIRED(name, STRING),
    FIELD_OPTIONAL(subsystem, STRING),
    FIELD_REQUIRED(owner, STRING),
    FIELD_REQUIRED(status, STRING),
    FIELD_REQUIRED(type, STRING),
    FIELD_REQUIRED(class, STRING),
    FIELD_OPTIONAL(retcode, STRING),
    FIELD_OPTIONAL(correlator, STRING),
    FIELD_REQUIRED(phase, NUMBER),
    FIELD_REQUIRED(phaseName, STRING)
);

struct Spool {};
ZJSON_SCHEMA(Spool,
    FIELD_REQUIRED(id, NUMBER),
    FIELD_REQUIRED(ddname, STRING),
    FIELD_REQUIRED(stepname, STRING),
    FIELD_REQUIRED(dsname, STRING),
    FIELD_REQUIRED(procstep, STRING)
);

struct UssItem {};
ZJSON_SCHEMA(UssItem,
    FIELD_REQUIRED(name, STRING),
    FIELD_OPTIONAL(links, NUMBER),
    FIELD_OPTIONAL(user, STRING),
    FIELD_OPTIONAL(group, STRING),
    FIELD_OPTIONAL(size, NUMBER),
    FIELD_OPTIONAL(filetag, STRING),
    FIELD_OPTIONAL(mtime, STRING),
    FIELD_OPTIONAL(mode, STRING)
);

struct IssueConsoleCmdResponse {};
ZJSON_SCHEMA(IssueConsoleCmdResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(data, STRING)
);

struct GetInfoResponse {};
ZJSON_SCHEMA(GetInfoResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(version, STRING),
    FIELD_REQUIRED(buildDate, STRING)
);

struct CreateDatasetResponse {};
ZJSON_SCHEMA(CreateDatasetResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct CreateMemberResponse {};
ZJSON_SCHEMA(CreateMemberResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct DeleteDatasetResponse {};
ZJSON_SCHEMA(DeleteDatasetResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct RenameDatasetResponse {};
ZJSON_SCHEMA(RenameDatasetResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct RenameMemberResponse {};
ZJSON_SCHEMA(RenameMemberResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct ListDatasetsResponse {};
ZJSON_SCHEMA(ListDatasetsResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED_OBJECT_ARRAY(items, Dataset),
    FIELD_REQUIRED(returnedRows, NUMBER)
);

struct ListDsMembersResponse {};
ZJSON_SCHEMA(ListDsMembersResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED_OBJECT_ARRAY(items, DsMember),
    FIELD_REQUIRED(returnedRows, NUMBER)
);

struct ReadDatasetResponse {};
ZJSON_SCHEMA(ReadDatasetResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_OPTIONAL(encoding, STRING),
    FIELD_REQUIRED(etag, STRING),
    FIELD_REQUIRED(data, STRING),
    FIELD_OPTIONAL(contentLen, NUMBER)
);

struct RestoreDatasetResponse {};
ZJSON_SCHEMA(RestoreDatasetResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct WriteDatasetResponse {};
ZJSON_SCHEMA(WriteDatasetResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(etag, STRING),
    FIELD_OPTIONAL(contentLen, NUMBER),
    FIELD_OPTIONAL(truncationWarning, STRING)
);

struct CopyDatasetResponse {};
ZJSON_SCHEMA(CopyDatasetResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct CancelJobResponse {};
ZJSON_SCHEMA(CancelJobResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct DeleteJobResponse {};
ZJSON_SCHEMA(DeleteJobResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct GetJclResponse {};
ZJSON_SCHEMA(GetJclResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(data, STRING)
);

struct GetJobStatusResponse {};
ZJSON_SCHEMA(GetJobStatusResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(id, STRING),
    FIELD_REQUIRED(name, STRING),
    FIELD_OPTIONAL(subsystem, STRING),
    FIELD_REQUIRED(owner, STRING),
    FIELD_REQUIRED(status, STRING),
    FIELD_REQUIRED(type, STRING),
    FIELD_REQUIRED(class, STRING),
    FIELD_OPTIONAL(retcode, STRING),
    FIELD_OPTIONAL(correlator, STRING),
    FIELD_REQUIRED(phase, NUMBER),
    FIELD_REQUIRED(phaseName, STRING)
);

struct HoldJobResponse {};
ZJSON_SCHEMA(HoldJobResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct ListJobsResponse {};
ZJSON_SCHEMA(ListJobsResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED_OBJECT_ARRAY(items, Job)
);

struct ListSpoolsResponse {};
ZJSON_SCHEMA(ListSpoolsResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED_OBJECT_ARRAY(items, Spool)
);

struct ReadSpoolResponse {};
ZJSON_SCHEMA(ReadSpoolResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_OPTIONAL(encoding, STRING),
    FIELD_REQUIRED(data, STRING)
);

struct ReleaseJobResponse {};
ZJSON_SCHEMA(ReleaseJobResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct SubmitJclResponse {};
ZJSON_SCHEMA(SubmitJclResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(jobId, STRING),
    FIELD_REQUIRED(jobName, STRING)
);

struct SubmitJobResponse {};
ZJSON_SCHEMA(SubmitJobResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(jobId, STRING),
    FIELD_REQUIRED(jobName, STRING)
);

struct SubmitUssResponse {};
ZJSON_SCHEMA(SubmitUssResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(jobId, STRING),
    FIELD_REQUIRED(jobName, STRING)
);

struct ToolSearchResponse {};
ZJSON_SCHEMA(ToolSearchResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(data, STRING)
);

struct IssueTsoCmdResponse {};
ZJSON_SCHEMA(IssueTsoCmdResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(data, STRING)
);

struct ChmodFileResponse {};
ZJSON_SCHEMA(ChmodFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct ChownFileResponse {};
ZJSON_SCHEMA(ChownFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct ChtagFileResponse {};
ZJSON_SCHEMA(ChtagFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct CopyUssResponse {};
ZJSON_SCHEMA(CopyUssResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct CreateFileResponse {};
ZJSON_SCHEMA(CreateFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct DeleteFileResponse {};
ZJSON_SCHEMA(DeleteFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

struct ListFilesResponse {};
ZJSON_SCHEMA(ListFilesResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED_OBJECT_ARRAY(items, UssItem),
    FIELD_REQUIRED(returnedRows, NUMBER)
);

struct ReadFileResponse {};
ZJSON_SCHEMA(ReadFileResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_OPTIONAL(encoding, STRING),
    FIELD_REQUIRED(etag, STRING),
    FIELD_REQUIRED(data, STRING),
    FIELD_OPTIONAL(contentLen, NUMBER)
);

struct WriteFileResponse {};
ZJSON_SCHEMA(WriteFileResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(etag, STRING),
    FIELD_REQUIRED(created, BOOL),
    FIELD_OPTIONAL(contentLen, NUMBER)
);

struct IssueUssCmdResponse {};
ZJSON_SCHEMA(IssueUssCmdResponse,
    FIELD_REQUIRED(success, BOOL),
    FIELD_REQUIRED(data, STRING)
);

struct MoveFileResponse {};
ZJSON_SCHEMA(MoveFileResponse,
    FIELD_REQUIRED(success, BOOL)
);

#endif
